Repository kgu-moneyplanet/moneyplanet-FE, pull requests merged in 2025-04, with the labels that each got.

#2 [Setting] #1 - 프로젝트 기초 세팅
  .github/ISSUE_TEMPLATE /-issue-template.md
  .github/pull_request_template.md
  .idea/runConfigurations/main_dart.xml
  lib/application/main.dart
  lib/application/tabBar/view/test.dart
  lib/application/tabBar/viewModel/test.dart
  lib/global/assets/images/test.JPG
  lib/global/components/test.dart
  lib/global/test.dart
  lib/main.dart
  lib/network/base/test.dart
  lib/network/domain/dto/request/test.dart
  lib/network/domain/dto/response/test.dart
  lib/network/test.dart
  lib/presentaion/chart/model/test.dart
  lib/presentaion/chart/test.dart
  lib/presentaion/chart/view/test.dart
  lib/presentaion/chart/viewModel/test.dart
  lib/presentaion/diary/model/test.dart
  lib/presentaion/diary/test.dart
  lib/presentaion/diary/view/test.dart
  lib/presentaion/diary/viewModel/test.dart
  lib/presentaion/home/model/test.dart
  lib/presentaion/home/test.dart
  lib/presentaion/home/view/test.dart
  lib/presentaion/home/viewModel/test.dart
  lib/presentaion/myPage/model/test.dart
  lib/presentaion/myPage/test.dart
  lib/presentaion/myPage/view/test.dart
  lib/presentaion/myPage/viewModel/test.dart
  lib/presentaion/onboarding/model/test.dart
  lib/presentaion/onboarding/test.dart
  lib/presentaion/onboarding/view/test.dart
  lib/presentaion/onboarding/viewModel/test.dart
  lib/presentaion/register/model/test.dart
  lib/presentaion/register/test.dart
  lib/presentaion/register/view/test.dart
  lib/presentaion/register/viewModel/test.dart
  lib/presentaion/splash/model/test.dart
  lib/presentaion/splash/test.dart
  lib/presentaion/splash/view/test.dart
  lib/presentaion/splash/viewModel/test.dart
  lib/presentaion/survey/model/test.dart
  lib/presentaion/survey/test.dart
  lib/presentaion/survey/view/test.dart
  lib/presentaion/survey/viewModel/test.dart
  pubspec.yaml
  test/widget_test.dart
Labels: Setting ⚙️, 한열 🧄

#4 [Docs] #3 - 컨벤션 및 프로젝트 세팅 관련 리드미 작성
  .github/pull_request_template.md
  README.md
Labels: Docs 📑, 한열 🧄

#6 [Feat] #5 - 기본 탭 바 세팅
  .gitignore
  README.md
  lib/application/main.dart
  lib/application/tabBar/model/tab_model.dart
  lib/application/tabBar/view/tab_screen.dart
  lib/application/tabBar/view/test.dart
  lib/application/tabBar/viewModel/tab_viewModel.dart
  lib/global/assets/fonts/SOYO Maple Regular.ttf
  lib/presentaion/chart/view/chart_screen.dart
  lib/presentaion/chart/view/test.dart
  lib/presentaion/diary/view/diary_screen.dart
  lib/presentaion/diary/view/test.dart
  lib/presentaion/home/view/home_screen.dart
  lib/presentaion/home/view/test.dart
  lib/presentaion/myPage/view/mypage_screen.dart
  lib/presentaion/myPage/view/test.dart
  lib/presentaion/register/view/register_screen.dart
Labels: Feat 💻, 한열 🧄

#9 [Chore] #8 - ㅌㅔ스트
  lib/application/main.dart
Labels: Feat 💻, 한열 🧄

#12 [Setting] #10 - asset 세팅
  lib/global/assets/fonts/Pretendard-Bold.ttf
  lib/global/assets/fonts/Pretendard-Medium.ttf
  lib/global/assets/fonts/Pretendard-Regular.ttf
  lib/global/assets/fonts/Pretendard-SemiBold.ttf
  lib/global/theme/colors.dart
  lib/global/theme/textStyles.dart
  lib/presentaion/home/view/home_screen.dart
  pubspec.yaml
Labels: Setting ⚙️, 한열 🧄

#15 [Style] #13 - 홈 화면 UI 구현
  analysis_options.yaml
  lib/global/assets/images/icons/bell_01.png
  lib/global/assets/images/icons/category_car.png
  lib/global/assets/images/icons/category_coffee.png
  lib/global/assets/images/icons/category_food.png
  lib/global/assets/images/icons/category_health.png
  lib/global/assets/images/icons/category_life.png
  lib/global/assets/images/icons/category_rest.png
  lib/global/assets/images/icons/category_shopping.png
  lib/global/assets/images/icons/help_circle.png
  lib/global/assets/images/planet_icon/planet1.png
  lib/global/assets/images/planet_icon/planet2.png
  lib/global/assets/images/planet_icon/planet3.png
  lib/global/assets/images/planet_icon/planet4.png
  lib/global/assets/images/planet_icon/planet5.png
  lib/global/assets/images/planet_icon/planet6.png
  lib/global/assets/images/planet_icon/planet7.png
  lib/global/assets/images/planet_icon/planet8.png
  lib/global/assets/images/planet_icon/planet_border.png
  lib/global/category_list.dart
  lib/global/components/consumption_item.dart
  lib/global/planet_list.dart
  lib/global/test.dart
  lib/presentaion/diary/model/diary_model.dart
  lib/presentaion/home/view/home_first_section.dart
  lib/presentaion/home/view/home_screen.dart
  lib/presentaion/home/view/home_second_section.dart
  lib/presentaion/home/view/home_third_section.dart
  pubspec.yaml
Labels: Style 🖼️, 한열 🧄

#21 [Style] #20 - 가계부 탭 UI 구현
  lib/application/main.dart
  lib/application/tabBar/viewModel/test.dart
  lib/global/components/consumption_item.dart
  lib/presentaion/diary/view/diary_screen.dart
  lib/presentaion/home/view/home_screen.dart
  pubspec.yaml
Labels: Style 🖼️, 한열 🧄

#23 [Style] #19 온보딩 UI 구현
  lib/global/assets/images/rocket1.png
  lib/presentaion/myPage/view/mypage_first_section.dart
  lib/presentaion/onboarding/view/guidetype_screen.dart
  lib/presentaion/onboarding/view/question_screen.dart
  lib/presentaion/onboarding/view/resulttype_screen.dart
  lib/presentaion/onboarding/view/selecttype_screen.dart
  lib/presentaion/onboarding/view/selecttype_screen1.dart
  lib/presentaion/onboarding/view/selecttype_screen2.dart
  lib/presentaion/onboarding/view/selecttype_screen3.dart
  lib/presentaion/onboarding/view/selecttype_screen4.dart
  lib/presentaion/onboarding/view/selecttype_screen5.dart
  lib/presentaion/onboarding/view/signup_screen.dart
  lib/presentaion/onboarding/view/signup_screen2.dart
  pubspec.yaml
Labels: Style 🖼️, 형준 🍙

#26 [Style] #24 도움말 UI 구현
  lib/global/assets/images/type_icon/artist_palette.png
  lib/global/assets/images/type_icon/crown.png
  lib/global/assets/images/type_icon/money_bag.png
  lib/global/assets/images/type_icon/objects.png
  lib/global/assets/images/type_icon/reading_glasses.png
  lib/global/assets/images/type_icon/rocket.png
  lib/global/assets/images/type_icon/roller_coaster.png
  lib/global/assets/images/type_icon/sparkles.png
  lib/global/assets/images/type_icon/type_cafe.png
  lib/global/assets/images/type_icon/type_food.png
  lib/global/assets/images/type_icon/type_shopping.png
  lib/global/planet_list.dart
  lib/presentaion/home/view/home_first_section.dart
  lib/presentaion/myPage/view/hint_abc_screen.dart
  lib/presentaion/myPage/view/hint_consumetype_screen.dart
  lib/presentaion/myPage/view/hint_screen.dart
  lib/presentaion/myPage/view/mypage_first_section.dart
  pubspec.yaml
Labels: Style 🖼️, 형준 🍙
