Repository kgu-moneyplanet/moneyplanet-FE, pull requests merged in 2025-05, with the labels that each got.

#29 [Style] #28 - 분석 차트 화면 구현
  .metadata
  android/app/build.gradle.kts
  assets/images/icons/arrow_square_downright.png
  assets/images/icons/arrow_square_upright.png
  lib/presentaion/chart/view/chart_first_section.dart
  lib/presentaion/chart/view/chart_fourth_section.dart
  lib/presentaion/chart/view/chart_screen.dart
  lib/presentaion/chart/view/chart_second_section.dart
  lib/presentaion/chart/view/chart_third_section.dart
  lib/presentaion/myPage/view/hint_abc_screen.dart
  lib/presentaion/myPage/view/mypage_third_section.dart
  lib/presentaion/onboarding/view/guidetype_screen.dart
  lib/presentaion/onboarding/view/selecttype_screen1.dart
  lib/presentaion/onboarding/view/selecttype_screen2.dart
  lib/presentaion/onboarding/view/selecttype_screen3.dart
  lib/presentaion/onboarding/view/selecttype_screen4.dart
  lib/presentaion/onboarding/view/selecttype_screen5.dart
  pubspec.yaml
Labels: Style 🖼️, 형준 🍙

#32 [Style] #31 가계부 작성 페이지UI
  lib/global/components/floating_dial_button.dart
  lib/main.dart
  lib/presentaion/register/view/register_screen.dart
Labels: Style 🖼️, 한열 🧄

#33 [Chore] #25 - 이미지들 변경 및 달력뷰 구현
  assets/images/icons/category_culture.png
  assets/images/icons/category_education.png
  assets/images/icons/category_event.png
  assets/images/icons/category_fashion.png
  assets/images/icons/category_home.png
  assets/images/icons/category_mart.png
  assets/images/icons/category_pet.png
  assets/images/icons/category_saving.png
  assets/images/icons/category_tax.png
  assets/images/planet_icon/planet1.png
  assets/images/planet_icon/planet2.png
  assets/images/planet_icon/planet3.png
  assets/images/planet_icon/planet4.png
  assets/images/planet_icon/planet5.png
  assets/images/planet_icon/planet6.png
  assets/images/planet_icon/planet7.png
  assets/images/planet_icon/planet8.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/global/components/consumption_item.dart
  lib/global/components/floating_dial_button.dart
  lib/presentaion/diary/model/diary_model.dart
  lib/presentaion/diary/view/diary_calendar_screen.dart
  lib/presentaion/diary/view/diary_screen.dart
  lib/presentaion/register/view/register_ocr_screen.dart
  lib/presentaion/register/view/register_screen.dart
  pubspec.yaml
Labels: Chore 🪡, 한열 🧄
